In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('cleaned_dataset.csv')
df

,serial_number,project_id,project_code,legacy_ocms_code,pmgid,project_name,agency,state,date_of_approval,start_date,...,risk_score,risk_class,target_cost,target_delay,target_future_cost,target_future_delay,target_future_risk,ministry_encoded,sector_encoded,state_encoded
0,1,40000,40000,-,-,CO CIVIL AVIATION REASEARCH ORG. (PH-II) AT BE...,AAI,ANDHRA PRADESH,2022-06-01,2022-07-01,...,1.0,High,246.00,10.0,NaN,NaN,NaN,0.016501,NaN,0.000272
1,11,40000,40000,-,-,C/O OF NITB AND ASSOCIATED WORK AT VIJAYAWADA ...,AAI,NaN,2022-06-01,2022-07-01,...,1.0,High,246.00,10.0,1.0,1.0,1.0,0.016501,NaN,NaN
2,21,40000,40000,-,-,10 Development of Dholera International Greenf...,AAI,NaN,2022-06-01,2022-07-01,...,1.0,High,246.00,10.0,NaN,NaN,NaN,0.016501,0.000163,NaN
3,12,40001,40001,-,-,RAJAHMUNDRY AIRPORT: CONSTRUCTION OF NEW DOMES...,AAI,NaN,2025-08-01,2024-07-01,...,1.0,High,231.85,15.0,1.0,1.0,1.0,0.169744,NaN,NaN
4,12,40001,40001,-,-,RAJAHMUNDRY AIRPORT: CONSTRUCTION OF NEW DOMES...,AAI,NaN,2025-08-01,2024-07-01,...,1.0,High,231.85,15.0,1.0,1.0,1.0,0.169744,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18358,1732,914467,914467,-,-,Amended BharatNet Program - BR,Department of Telecommunications,PAN India,2023-08-01,2025-03-01,...,0.0,Low,0.00,NaN,NaN,NaN,NaN,0.010292,NaN,0.003050
18359,1733,938832,938832,-,-,Amended BharatNet Program - RJ,Department of Telecommunications,PAN India,2023-08-01,2026-03-01,...,0.0,Low,0.00,NaN,NaN,NaN,NaN,0.010292,NaN,0.003050
18360,504,944288,944288,-,-,Super accelerated cooling system (Uniform Cool...,Steel Authority of India Limited (SAIL),Chhattisgarh,2025-06-01,2025-06-01,...,0.0,Low,0.00,NaN,NaN,NaN,NaN,0.013887,0.011708,0.021728
18361,1734,946208,946208,-,-,Amended BharatNet Program - SKM,Department of Telecommunications,PAN India,2023-08-01,2026-06-01,...,0.0,Low,0.00,NaN,NaN,NaN,NaN,0.010292,NaN,0.003050
18362,1735,976009,976009,-,-,"Amended BharatNet Program - ARP, NGL, MNP",Department of Telecommunications,PAN India,2023-08-01,2025-06-01,...,0.0,Low,0.00,NaN,NaN,NaN,NaN,0.010292,NaN,0.003050

In [8]:
filtered_df = df[df['project_name'] == 'BharatNet']
filtered_df.head()

,serial_number,project_id,project_code,legacy_ocms_code,pmgid,project_name,agency,state,date_of_approval,start_date,...,risk_score,risk_class,target_cost,target_delay,target_future_cost,target_future_delay,target_future_risk,ministry_encoded,sector_encoded,state_encoded
0,1,40000,40000,-,-,BharatNet,AAI,ANDHRA PRADESH,2022-06-01,2022-07-01,...,1.0,High,246.00,10.0,NaN,NaN,NaN,0.016501,NaN,0.000272
1,11,40000,40000,-,-,BharatNet,AAI,NaN,2022-06-01,2022-07-01,...,1.0,High,246.00,10.0,1.0,1.0,1.0,0.016501,NaN,NaN
2,21,40000,40000,-,-,BharatNet,AAI,NaN,2022-06-01,2022-07-01,...,1.0,High,246.00,10.0,NaN,NaN,NaN,0.016501,0.000163,NaN
3,12,40001,40001,-,-,BharatNet,AAI,NaN,2025-08-01,2024-07-01,...,1.0,High,231.85,15.0,1.0,1.0,1.0,0.169744,NaN,NaN
4,12,40001,40001,-,-,BharatNet,AAI,NaN,2025-08-01,2024-07-01,...,1.0,High,231.85,15.0,1.0,1.0,1.0,0.169744,NaN,NaN